//---------------------------------------------------------------------------
#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <Tabnotbk.hpp>
#include <ExtCtrls.hpp>
#include <Menus.hpp>
#include <Dialogs.hpp>
//---------------------------------------------------------------------------
class TFormPrincipal : public TForm
{
__published:	// IDE-managed Components
    TPageControl *PagePrincipal;
    TTabSheet *TabUSPR_1;
    TTabSheet *TabUSPR_2;
    TTabSheet *TabUSPR_3;
    TTabSheet *TabUSPR_4;
    TTabSheet *TabUSPR_5;
    TTabSheet *TabUSPR_6;
    TTabSheet *TabUSPR_7;
    TTabSheet *TabUSPR_8;
    TGroupBox *GroupGeral_1;
    TCheckBox *CheckKey_1;
    TCheckBox *CheckTransp_1;
    TCheckBox *CheckReverb_1;
    TCheckBox *CheckChorus_1;
    TScrollBar *ScrollTransp_1;
    TScrollBar *ScrollReverb_1;
    TScrollBar *ScrollChorus_1;
    TLabel *LabelTransp_1;
    TLabel *LabelReverb_1;
    TLabel *LabelChorus_1;
    TGroupBox *GroupUppers_1;
    TCheckBox *CheckUP1_1;
    TCheckBox *CheckUP2_1;
    TComboBox *ComboUP1_1;
    TComboBox *ComboUP2_1;
    TLabel *LabelUP2Vol_1;
    TLabel *LabelUP1Vol_1;
    TScrollBar *ScrollUP1Vol_1;
    TScrollBar *ScrollUP2Vol_1;
    TScrollBar *ScrollUP1Oct_1;
    TLabel *LabelUP1Oct_1;
    TScrollBar *ScrollUP2Oct_1;
    TLabel *LabelUP2Oct_1;
    TRadioGroup *RadioUP2State_1;
    TRadioButton *RadioUP2Desativado_1;
    TRadioButton *RadioUP2MelInt_1;
    TRadioButton *RadioUP2Layer_1;
    TGroupBox *GroupMBassMDrums_1;
    TLabel *LabelMBassVol_1;
    TCheckBox *CheckMDrums_1;
    TCheckBox *CheckMBass_1;
    TComboBox *ComboMBass_1;
    TComboBox *ComboMDrums_1;
    TScrollBar *ScrollMBassVol_1;
    TLabel *LabelTempo_1;
    TEdit *EditTempo_1;
    TGroupBox *GroupLower_1;
    TLabel *LabelLowerVol_1;
    TLabel *LabelLowerOct_1;
    TLabel *LabelSplitLower_1;
    TCheckBox *CheckLower_1;
    TComboBox *ComboLower_1;
    TScrollBar *ScrollLowerVol_1;
    TScrollBar *ScrollSplitLower_1;
    TScrollBar *ScrollLowerOct_1;
    TCheckBox *CheckLowerInt_1;
    TCheckBox *CheckLowerMem_1;
    TLabel *LabelSplitLowerNote_1;
    TGroupBox *GroupGeral_2;
    TLabel *LabelTransp_2;
    TLabel *LabelReverb_2;
    TLabel *LabelChorus_2;
    TLabel *LabelTempo_2;
    TCheckBox *CheckKey_2;
    TCheckBox *CheckTransp_2;
    TCheckBox *CheckReverb_2;
    TCheckBox *CheckChorus_2;
    TScrollBar *ScrollTransp_2;
    TScrollBar *ScrollReverb_2;
    TScrollBar *ScrollChorus_2;
    TEdit *EditTempo_2;
    TGroupBox *GroupMBassMDrums_2;
    TLabel *LabelMBassVol_2;
    TCheckBox *CheckMDrums_2;
    TCheckBox *CheckMBass_2;
    TComboBox *ComboMBass_2;
    TComboBox *ComboMDrums_2;
    TScrollBar *ScrollMBassVol_2;
    TGroupBox *GroupUppers_2;
    TLabel *LabelUP2Vol_2;
    TLabel *LabelUP1Vol_2;
    TLabel *LabelUP1Oct_2;
    TLabel *LabelUP2Oct_2;
    TCheckBox *CheckUP1_2;
    TCheckBox *CheckUP2_2;
    TComboBox *ComboUP1_2;
    TComboBox *ComboUP2_2;
    TScrollBar *ScrollUP1Vol_2;
    TScrollBar *ScrollUP2Vol_2;
    TScrollBar *ScrollUP1Oct_2;
    TScrollBar *ScrollUP2Oct_2;
    TRadioGroup *RadioUP2State_2;
    TRadioButton *RadioUP2Desativado_2;
    TRadioButton *RadioUP2MelInt_2;
    TRadioButton *RadioUP2Layer_2;
    TGroupBox *GroupLower_2;
    TLabel *LabelLowerVol_2;
    TLabel *LabelLowerOct_2;
    TLabel *LabelSplitLower_2;
    TLabel *LabelSplitLowerNote_2;
    TCheckBox *CheckLower_2;
    TComboBox *ComboLower_2;
    TScrollBar *ScrollLowerVol_2;
    TScrollBar *ScrollSplitLower_2;
    TScrollBar *ScrollLowerOct_2;
    TCheckBox *CheckLowerInt_2;
    TCheckBox *CheckLowerMem_2;
    TGroupBox *GroupGeral_3;
    TLabel *LabelTransp_3;
    TLabel *LabelReverb_3;
    TLabel *LabelChorus_3;
    TLabel *LabelTempo_3;
    TCheckBox *CheckKey_3;
    TCheckBox *CheckTransp_3;
    TCheckBox *CheckReverb_3;
    TCheckBox *CheckChorus_3;
    TScrollBar *ScrollTransp_3;
    TScrollBar *ScrollReverb_3;
    TScrollBar *ScrollChorus_3;
    TEdit *EditTempo_3;
    TGroupBox *GroupMBassMDrums_3;
    TLabel *LabelMBassVol_3;
    TCheckBox *CheckMDrums_3;
    TCheckBox *CheckMBass_3;
    TComboBox *ComboMBass_3;
    TComboBox *ComboMDrums_3;
    TScrollBar *ScrollMBassVol_3;
    TGroupBox *GroupUppers_3;
    TLabel *LabelUP2Vol_3;
    TLabel *LabelUP1Vol_3;
    TLabel *LabelUP1Oct_3;
    TLabel *LabelUP2Oct_3;
    TCheckBox *CheckUP1_3;
    TCheckBox *CheckUP2_3;
    TComboBox *ComboUP1_3;
    TComboBox *ComboUP2_3;
    TScrollBar *ScrollUP1Vol_3;
    TScrollBar *ScrollUP2Vol_3;
    TScrollBar *ScrollUP1Oct_3;
    TScrollBar *ScrollUP2Oct_3;
    TRadioGroup *RadioUP2State_3;
    TRadioButton *RadioUP2Desativado_3;
    TRadioButton *RadioUP2MelInt_3;
    TRadioButton *RadioUP2Layer_3;
    TGroupBox *GroupLower_3;
    TLabel *LabelLowerVol_3;
    TLabel *LabelLowerOct_3;
    TLabel *LabelSplitLower_3;
    TLabel *LabelSplitLowerNote_3;
    TCheckBox *CheckLower_3;
    TComboBox *ComboLower_3;
    TScrollBar *ScrollLowerVol_3;
    TScrollBar *ScrollSplitLower_3;
    TScrollBar *ScrollLowerOct_3;
    TCheckBox *CheckLowerInt_3;
    TCheckBox *CheckLowerMem_3;
    TGroupBox *GroupGeral_4;
    TLabel *LabelTransp_4;
    TLabel *LabelReverb_4;
    TLabel *LabelChorus_4;
    TLabel *LabelTempo_4;
    TCheckBox *CheckKey_4;
    TCheckBox *CheckTransp_4;
    TCheckBox *CheckReverb_4;
    TCheckBox *CheckChorus_4;
    TScrollBar *ScrollTransp_4;
    TScrollBar *ScrollReverb_4;
    TScrollBar *ScrollChorus_4;
    TEdit *EditTempo_4;
    TGroupBox *GroupMBassMDrums_4;
    TLabel *LabelMBassVol_4;
    TCheckBox *CheckMDrums_4;
    TCheckBox *CheckMBass_4;
    TComboBox *ComboMBass_4;
    TComboBox *ComboMDrums_4;
    TScrollBar *ScrollMBassVol_4;
    TGroupBox *GroupUppers_4;
    TLabel *LabelUP2Vol_4;
    TLabel *LabelUP1Vol_4;
    TLabel *LabelUP1Oct_4;
    TLabel *LabelUP2Oct_4;
    TCheckBox *CheckUP1_4;
    TCheckBox *CheckUP2_4;
    TComboBox *ComboUP1_4;
    TComboBox *ComboUP2_4;
    TScrollBar *ScrollUP1Vol_4;
    TScrollBar *ScrollUP2Vol_4;
    TScrollBar *ScrollUP1Oct_4;
    TScrollBar *ScrollUP2Oct_4;
    TRadioGroup *RadioUP2State_4;
    TRadioButton *RadioUP2Desativado_4;
    TRadioButton *RadioUP2MelInt_4;
    TRadioButton *RadioUP2Layer_4;
    TGroupBox *GroupLower_4;
    TLabel *LabelLowerVol_4;
    TLabel *LabelLowerOct_4;
    TLabel *LabelSplitLower_4;
    TLabel *LabelSplitLowerNote_4;
    TCheckBox *CheckLower_4;
    TComboBox *ComboLower_4;
    TScrollBar *ScrollLowerVol_4;
    TScrollBar *ScrollSplitLower_4;
    TScrollBar *ScrollLowerOct_4;
    TCheckBox *CheckLowerInt_4;
    TCheckBox *CheckLowerMem_4;
    TGroupBox *GroupGeral_5;
    TLabel *LabelTransp_5;
    TLabel *LabelReverb_5;
    TLabel *LabelChorus_5;
    TLabel *LabelTempo_5;
    TCheckBox *CheckKey_5;
    TCheckBox *CheckTransp_5;
    TCheckBox *CheckReverb_5;
    TCheckBox *CheckChorus_5;
    TScrollBar *ScrollTransp_5;
    TScrollBar *ScrollReverb_5;
    TScrollBar *ScrollChorus_5;
    TEdit *EditTempo_5;
    TGroupBox *GroupMBassMDrums_5;
    TLabel *LabelMBassVol_5;
    TCheckBox *CheckMDrums_5;
    TCheckBox *CheckMBass_5;
    TComboBox *ComboMBass_5;
    TComboBox *ComboMDrums_5;
    TScrollBar *ScrollMBassVol_5;
    TGroupBox *GroupUppers_5;
    TLabel *LabelUP2Vol_5;
    TLabel *LabelUP1Vol_5;
    TLabel *LabelUP1Oct_5;
    TLabel *LabelUP2Oct_5;
    TCheckBox *CheckUP1_5;
    TCheckBox *CheckUP2_5;
    TComboBox *ComboUP1_5;
    TComboBox *ComboUP2_5;
    TScrollBar *ScrollUP1Vol_5;
    TScrollBar *ScrollUP2Vol_5;
    TScrollBar *ScrollUP1Oct_5;
    TScrollBar *ScrollUP2Oct_5;
    TRadioGroup *RadioUP2State_5;
    TRadioButton *RadioUP2Desativado_5;
    TRadioButton *RadioUP2MelInt_5;
    TRadioButton *RadioUP2Layer_5;
    TGroupBox *GroupLower_5;
    TLabel *LabelLowerVol_5;
    TLabel *LabelLowerOct_5;
    TLabel *LabelSplitLower_5;
    TLabel *LabelSplitLowerNote_5;
    TCheckBox *CheckLower_5;
    TComboBox *ComboLower_5;
    TScrollBar *ScrollLowerVol_5;
    TScrollBar *ScrollSplitLower_5;
    TScrollBar *ScrollLowerOct_5;
    TCheckBox *CheckLowerInt_5;
    TCheckBox *CheckLowerMem_5;
    TGroupBox *GroupGeral_6;
    TLabel *LabelTransp_6;
    TLabel *LabelReverb_6;
    TLabel *LabelChorus_6;
    TLabel *LabelTempo_6;
    TCheckBox *CheckKey_6;
    TCheckBox *CheckTransp_6;
    TCheckBox *CheckReverb_6;
    TCheckBox *CheckChorus_6;
    TScrollBar *ScrollTransp_6;
    TScrollBar *ScrollReverb_6;
    TScrollBar *ScrollChorus_6;
    TEdit *EditTempo_6;
    TGroupBox *GroupMBassMDrums_6;
    TLabel *LabelMBassVol_6;
    TCheckBox *CheckMDrums_6;
    TCheckBox *CheckMBass_6;
    TComboBox *ComboMBass_6;
    TComboBox *ComboMDrums_6;
    TScrollBar *ScrollMBassVol_6;
    TGroupBox *GroupUppers_6;
    TLabel *LabelUP2Vol_6;
    TLabel *LabelUP1Vol_6;
    TLabel *LabelUP1Oct_6;
    TLabel *LabelUP2Oct_6;
    TCheckBox *CheckUP1_6;
    TCheckBox *CheckUP2_6;
    TComboBox *ComboUP1_6;
    TComboBox *ComboUP2_6;
    TScrollBar *ScrollUP1Vol_6;
    TScrollBar *ScrollUP2Vol_6;
    TScrollBar *ScrollUP1Oct_6;
    TScrollBar *ScrollUP2Oct_6;
    TRadioGroup *RadioUP2State_6;
    TRadioButton *RadioUP2Desativado_6;
    TRadioButton *RadioUP2MelInt_6;
    TRadioButton *RadioUP2Layer_6;
    TGroupBox *GroupLower_6;
    TLabel *LabelLowerVol_6;
    TLabel *LabelLowerOct_6;
    TLabel *LabelSplitLower_6;
    TLabel *LabelSplitLowerNote_6;
    TCheckBox *CheckLower_6;
    TComboBox *ComboLower_6;
    TScrollBar *ScrollLowerVol_6;
    TScrollBar *ScrollSplitLower_6;
    TScrollBar *ScrollLowerOct_6;
    TCheckBox *CheckLowerInt_6;
    TCheckBox *CheckLowerMem_6;
    TGroupBox *GroupGeral_7;
    TLabel *LabelTransp_7;
    TLabel *LabelReverb_7;
    TLabel *LabelChorus_7;
    TLabel *LabelTempo_7;
    TCheckBox *CheckKey_7;
    TCheckBox *CheckTransp_7;
    TCheckBox *CheckReverb_7;
    TCheckBox *CheckChorus_7;
    TScrollBar *ScrollTransp_7;
    TScrollBar *ScrollReverb_7;
    TScrollBar *ScrollChorus_7;
    TEdit *EditTempo_7;
    TGroupBox *GroupMBassMDrums_7;
    TLabel *LabelMBassVol_7;
    TCheckBox *CheckMDrums_7;
    TCheckBox *CheckMBass_7;
    TComboBox *ComboMBass_7;
    TComboBox *ComboMDrums_7;
    TScrollBar *ScrollMBassVol_7;
    TGroupBox *GroupUppers_7;
    TLabel *LabelUP2Vol_7;
    TLabel *LabelUP1Vol_7;
    TLabel *LabelUP1Oct_7;
    TLabel *LabelUP2Oct_7;
    TCheckBox *CheckUP1_7;
    TCheckBox *CheckUP2_7;
    TComboBox *ComboUP1_7;
    TComboBox *ComboUP2_7;
    TScrollBar *ScrollUP1Vol_7;
    TScrollBar *ScrollUP2Vol_7;
    TScrollBar *ScrollUP1Oct_7;
    TScrollBar *ScrollUP2Oct_7;
    TRadioGroup *RadioUP2State_7;
    TRadioButton *RadioUP2Desativado_7;
    TRadioButton *RadioUP2MelInt_7;
    TRadioButton *RadioUP2Layer_7;
    TGroupBox *GroupLower_7;
    TLabel *LabelLowerVol_7;
    TLabel *LabelLowerOct_7;
    TLabel *LabelSplitLower_7;
    TLabel *LabelSplitLowerNote_7;
    TCheckBox *CheckLower_7;
    TComboBox *ComboLower_7;
    TScrollBar *ScrollLowerVol_7;
    TScrollBar *ScrollSplitLower_7;
    TScrollBar *ScrollLowerOct_7;
    TCheckBox *CheckLowerInt_7;
    TCheckBox *CheckLowerMem_7;
    TGroupBox *GroupGeral_8;
    TLabel *LabelTransp_8;
    TLabel *LabelReverb_8;
    TLabel *LabelChorus_8;
    TLabel *LabelTempo_8;
    TCheckBox *CheckKey_8;
    TCheckBox *CheckTransp_8;
    TCheckBox *CheckReverb_8;
    TCheckBox *CheckChorus_8;
    TScrollBar *ScrollTransp_8;
    TScrollBar *ScrollReverb_8;
    TScrollBar *ScrollChorus_8;
    TEdit *EditTempo_8;
    TGroupBox *GroupMBassMDrums_8;
    TLabel *LabelMBassVol_8;
    TCheckBox *CheckMDrums_8;
    TCheckBox *CheckMBass_8;
    TComboBox *ComboMBass_8;
    TComboBox *ComboMDrums_8;
    TScrollBar *ScrollMBassVol_8;
    TGroupBox *GroupUppers_8;
    TLabel *LabelUP2Vol_8;
    TLabel *LabelUP1Vol_8;
    TLabel *LabelUP1Oct_8;
    TLabel *LabelUP2Oct_8;
    TCheckBox *CheckUP1_8;
    TCheckBox *CheckUP2_8;
    TComboBox *ComboUP1_8;
    TComboBox *ComboUP2_8;
    TScrollBar *ScrollUP1Vol_8;
    TScrollBar *ScrollUP2Vol_8;
    TScrollBar *ScrollUP1Oct_8;
    TScrollBar *ScrollUP2Oct_8;
    TRadioGroup *RadioUP2State_8;
    TRadioButton *RadioUP2Desativado_8;
    TRadioButton *RadioUP2MelInt_8;
    TRadioButton *RadioUP2Layer_8;
    TGroupBox *GroupLower_8;
    TLabel *LabelLowerVol_8;
    TLabel *LabelLowerOct_8;
    TLabel *LabelSplitLower_8;
    TLabel *LabelSplitLowerNote_8;
    TCheckBox *CheckLower_8;
    TComboBox *ComboLower_8;
    TScrollBar *ScrollLowerVol_8;
    TScrollBar *ScrollSplitLower_8;
    TScrollBar *ScrollLowerOct_8;
    TCheckBox *CheckLowerInt_8;
    TCheckBox *CheckLowerMem_8;
    TMainMenu *MainMenu1;
    TMenuItem *MenuFile;
    TMenuItem *MenuOpen;
    TMenuItem *MenuSaveAs;
    TMenuItem *MenuNew;
    TMenuItem *MenuEdit;
    TMenuItem *N1;
    TMenuItem *MenuClose;
    TMenuItem *MenuCopyUSPR;
    TMenuItem *MenuPasteUSPR;
    TOpenDialog *OpenDialog;
    TSaveDialog *SaveDialog;
    TMenuItem *MenuSave;
    TMenuItem *MenuOptions;
    TMenuItem *MenuAbout0;
    TMenuItem *MenuLanguage;
    TMenuItem *MenuAbout;
    TMenuItem *English1;
    TMenuItem *Portugues1;
    TMenuItem *MenuWhereStyles;
    TRichEdit *RichEditImprimir;
    TPrintDialog *PrintDialog1;
    TMenuItem *MenuImprimir;
    void __fastcall ScrollTransp_1Change(TObject *Sender);
    void __fastcall ScrollTransp_2Change(TObject *Sender);
    void __fastcall ScrollTransp_3Change(TObject *Sender);
    void __fastcall ScrollTransp_4Change(TObject *Sender);
    void __fastcall ScrollTransp_5Change(TObject *Sender);
    void __fastcall ScrollTransp_6Change(TObject *Sender);
    void __fastcall ScrollTransp_7Change(TObject *Sender);
    void __fastcall ScrollTransp_8Change(TObject *Sender);
    void __fastcall ScrollReverb_1Change(TObject *Sender);
    void __fastcall ScrollReverb_2Change(TObject *Sender);
    void __fastcall ScrollReverb_3Change(TObject *Sender);
    void __fastcall ScrollReverb_4Change(TObject *Sender);
    void __fastcall ScrollReverb_5Change(TObject *Sender);
    void __fastcall ScrollReverb_6Change(TObject *Sender);
    void __fastcall ScrollReverb_7Change(TObject *Sender);
    void __fastcall ScrollReverb_8Change(TObject *Sender);
    void __fastcall ScrollChorus_1Change(TObject *Sender);
    void __fastcall ScrollChorus_2Change(TObject *Sender);
    void __fastcall ScrollChorus_3Change(TObject *Sender);
    void __fastcall ScrollChorus_4Change(TObject *Sender);
    void __fastcall ScrollChorus_5Change(TObject *Sender);
    void __fastcall ScrollChorus_6Change(TObject *Sender);
    void __fastcall ScrollChorus_7Change(TObject *Sender);
    void __fastcall ScrollChorus_8Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_1Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_2Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_3Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_4Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_5Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_6Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_7Change(TObject *Sender);
    void __fastcall ScrollUP1Vol_8Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_1Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_2Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_3Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_4Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_5Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_6Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_7Change(TObject *Sender);
    void __fastcall ScrollUP2Vol_8Change(TObject *Sender);
    void __fastcall ScrollLowerVol_1Change(TObject *Sender);
    void __fastcall ScrollLowerVol_2Change(TObject *Sender);
    void __fastcall ScrollLowerVol_3Change(TObject *Sender);
    void __fastcall ScrollLowerVol_4Change(TObject *Sender);
    void __fastcall ScrollLowerVol_5Change(TObject *Sender);
    void __fastcall ScrollLowerVol_6Change(TObject *Sender);
    void __fastcall ScrollLowerVol_7Change(TObject *Sender);
    void __fastcall ScrollLowerVol_8Change(TObject *Sender);
    void __fastcall ScrollMBassVol_1Change(TObject *Sender);
    void __fastcall ScrollMBassVol_2Change(TObject *Sender);
    void __fastcall ScrollMBassVol_3Change(TObject *Sender);
    void __fastcall ScrollMBassVol_4Change(TObject *Sender);
    void __fastcall ScrollMBassVol_5Change(TObject *Sender);
    void __fastcall ScrollMBassVol_6Change(TObject *Sender);
    void __fastcall ScrollMBassVol_7Change(TObject *Sender);
    void __fastcall ScrollMBassVol_8Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_1Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_2Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_3Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_4Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_5Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_6Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_7Change(TObject *Sender);
    void __fastcall ScrollUP1Oct_8Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_1Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_2Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_3Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_4Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_5Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_6Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_7Change(TObject *Sender);
    void __fastcall ScrollUP2Oct_8Change(TObject *Sender);
    void __fastcall ScrollLowerOct_1Change(TObject *Sender);
    void __fastcall ScrollLowerOct_2Change(TObject *Sender);
    void __fastcall ScrollLowerOct_3Change(TObject *Sender);
    void __fastcall ScrollLowerOct_4Change(TObject *Sender);
    void __fastcall ScrollLowerOct_5Change(TObject *Sender);
    void __fastcall ScrollLowerOct_6Change(TObject *Sender);
    void __fastcall ScrollLowerOct_7Change(TObject *Sender);
    void __fastcall ScrollLowerOct_8Change(TObject *Sender);
    void __fastcall ScrollSplitLower_1Change(TObject *Sender);
    void __fastcall ScrollSplitLower_2Change(TObject *Sender);
    void __fastcall ScrollSplitLower_3Change(TObject *Sender);
    void __fastcall ScrollSplitLower_4Change(TObject *Sender);
    void __fastcall ScrollSplitLower_5Change(TObject *Sender);
    void __fastcall ScrollSplitLower_6Change(TObject *Sender);
    void __fastcall ScrollSplitLower_7Change(TObject *Sender);
    void __fastcall ScrollSplitLower_8Change(TObject *Sender);
    void __fastcall CheckLower_1Click(TObject *Sender);
    void __fastcall CheckLower_2Click(TObject *Sender);
    void __fastcall CheckLower_3Click(TObject *Sender);
    void __fastcall CheckLower_4Click(TObject *Sender);
    void __fastcall CheckLower_5Click(TObject *Sender);
    void __fastcall CheckLower_6Click(TObject *Sender);
    void __fastcall CheckLower_7Click(TObject *Sender);
    void __fastcall CheckLower_8Click(TObject *Sender);
    void __fastcall CheckMDrums_1Click(TObject *Sender);
    void __fastcall CheckMDrums_2Click(TObject *Sender);
    void __fastcall CheckMDrums_3Click(TObject *Sender);
    void __fastcall CheckMDrums_4Click(TObject *Sender);
    void __fastcall CheckMDrums_5Click(TObject *Sender);
    void __fastcall CheckMDrums_6Click(TObject *Sender);
    void __fastcall CheckMDrums_7Click(TObject *Sender);
    void __fastcall CheckMDrums_8Click(TObject *Sender);
    void __fastcall EditTempo_1KeyPress(TObject *Sender, char &Key);
    void __fastcall EditTempo_1Exit(TObject *Sender);
    void __fastcall EditTempo_2Exit(TObject *Sender);
    void __fastcall EditTempo_3Exit(TObject *Sender);
    void __fastcall EditTempo_4Exit(TObject *Sender);
    void __fastcall EditTempo_5Exit(TObject *Sender);
    void __fastcall EditTempo_6Exit(TObject *Sender);
    void __fastcall EditTempo_7Exit(TObject *Sender);
    void __fastcall EditTempo_8Exit(TObject *Sender);
    void __fastcall ScrollTransp_1Exit(TObject *Sender);
    void __fastcall ScrollTransp_2Exit(TObject *Sender);
    void __fastcall ScrollTransp_3Exit(TObject *Sender);
    void __fastcall ScrollTransp_4Exit(TObject *Sender);
    void __fastcall ScrollTransp_5Exit(TObject *Sender);
    void __fastcall ScrollTransp_6Exit(TObject *Sender);
    void __fastcall ScrollTransp_7Exit(TObject *Sender);
    void __fastcall ScrollTransp_8Exit(TObject *Sender);
    void __fastcall RadioUP2Desativado_1Click(TObject *Sender);
    void __fastcall RadioUP2Desativado_2Click(TObject *Sender);
    void __fastcall RadioUP2Desativado_3Click(TObject *Sender);
    void __fastcall RadioUP2Desativado_4Click(TObject *Sender);
    void __fastcall RadioUP2Desativado_5Click(TObject *Sender);
    void __fastcall RadioUP2Desativado_6Click(TObject *Sender);
    void __fastcall RadioUP2Desativado_7Click(TObject *Sender);
    void __fastcall RadioUP2Desativado_8Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_1Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_2Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_3Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_4Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_5Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_6Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_7Click(TObject *Sender);
    void __fastcall RadioUP2MelInt_8Click(TObject *Sender);
    void __fastcall RadioUP2Layer_1Click(TObject *Sender);
    void __fastcall RadioUP2Layer_2Click(TObject *Sender);
    void __fastcall RadioUP2Layer_3Click(TObject *Sender);
    void __fastcall RadioUP2Layer_4Click(TObject *Sender);
    void __fastcall RadioUP2Layer_5Click(TObject *Sender);
    void __fastcall RadioUP2Layer_6Click(TObject *Sender);
    void __fastcall RadioUP2Layer_7Click(TObject *Sender);
    void __fastcall RadioUP2Layer_8Click(TObject *Sender);
    void __fastcall PagePrincipalChange(TObject *Sender);
    void __fastcall MenuCloseClick(TObject *Sender);
    void __fastcall MenuOpenClick(TObject *Sender);
    void __fastcall MenuSaveAsClick(TObject *Sender);
    void __fastcall PagePrincipalChanging(TObject *Sender,
          bool &AllowChange);
    void __fastcall MenuSaveClick(TObject *Sender);
    void __fastcall MenuNewClick(TObject *Sender);
    void __fastcall MenuCopyUSPRClick(TObject *Sender);
    void __fastcall MenuPasteUSPRClick(TObject *Sender);
    void __fastcall English1Click(TObject *Sender);
    void __fastcall Portugues1Click(TObject *Sender);
    void __fastcall FormCloseQuery(TObject *Sender, bool &CanClose);
    void __fastcall MenuAboutClick(TObject *Sender);
    void __fastcall MenuWhereStylesClick(TObject *Sender);
    void __fastcall MenuImprimirClick(TObject *Sender);
private:	// User declarations
    AnsiString Caminho_Abrir;  //variaveis auxiliares para o "SalvarComo"
    AnsiString Caminho_Salvar;
public:		// User declarations
    void __fastcall matriz_para_uspr(int qual_uspr);   //qual_uspr, define se todos ou apenas um uspr será carregado
                                                       // dará suporte às funções de Copiar e Colar USPRs
    //faz execuções de EditTempoExit() e ScrollTransp_1Exit
    //para corrigir a função de Cópia de USPR
    void __fastcall CorrigeTempoTranspose();


    __fastcall TFormPrincipal(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TFormPrincipal *FormPrincipal;
//---------------------------------------------------------------------------
#endif
